

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

Extension host agent listening on 40519

[19:30:33] Extension host agent started.
[19:30:34] [127.0.0.1][0cead24b][ManagementConnection] New connection established.
[19:30:34] [127.0.0.1][c06d8e34][ExtensionHostConnection] New connection established.
[19:30:34] [127.0.0.1][c06d8e34][ExtensionHostConnection] <2650> Launched Extension Host Process.
rejected promise not handled within 1 second: Error: Could not find pty with id "1"
stack trace: Error: Could not find pty with id "1",    at M._throwIfNoPty (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:5468),    at M.updateTitle (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:2172),    at Object.call (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:13:8402),    at f.onPromise (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4940),    at f.onRawMessage (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4299),    at /home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:3552,    at D.fire (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.S (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:6:32863),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[Error: Could not find pty with id "1",    at M._throwIfNoPty (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:5468),    at M.updateTitle (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:2172),    at Object.call (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:13:8402),    at f.onPromise (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4940),    at f.onRawMessage (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4299),    at /home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:3552,    at D.fire (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.S (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:6:32863),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)]
rejected promise not handled within 1 second: Error: Could not find pty with id "1"
stack trace: Error: Could not find pty with id "1",    at M._throwIfNoPty (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:5468),    at M.updateIcon (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:2232),    at Object.call (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:13:8402),    at f.onPromise (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4940),    at f.onRawMessage (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4299),    at /home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:3552,    at D.fire (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.S (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:6:32863),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[Error: Could not find pty with id "1",    at M._throwIfNoPty (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:5468),    at M.updateIcon (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:2232),    at Object.call (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:13:8402),    at f.onPromise (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4940),    at f.onRawMessage (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4299),    at /home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:3552,    at D.fire (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.S (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:6:32863),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)]
[19:30:47] [127.0.0.1][0cead24b][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[19:30:48] [127.0.0.1][c06d8e34][ExtensionHostConnection] <2650> Extension Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[19:30:48] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[19:30:54] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[19:30:54] Cancelling previous shutdown timeout
[19:30:55] [127.0.0.1][a8d8bc89][ManagementConnection] New connection established.
[19:30:56] [127.0.0.1][aae6b3fd][ExtensionHostConnection] New connection established.
[19:30:56] [127.0.0.1][aae6b3fd][ExtensionHostConnection] <2761> Launched Extension Host Process.
rejected promise not handled within 1 second: Error: Could not find pty with id "3"
stack trace: Error: Could not find pty with id "3",    at M._throwIfNoPty (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:5468),    at M.updateTitle (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:2172),    at Object.call (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:13:8402),    at f.onPromise (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4940),    at f.onRawMessage (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4299),    at /home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:3552,    at D.fire (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.S (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:6:32863),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[Error: Could not find pty with id "3",    at M._throwIfNoPty (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:5468),    at M.updateTitle (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:2172),    at Object.call (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:13:8402),    at f.onPromise (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4940),    at f.onRawMessage (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4299),    at /home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:3552,    at D.fire (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.S (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:6:32863),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)]
rejected promise not handled within 1 second: Error: Could not find pty with id "3"
stack trace: Error: Could not find pty with id "3",    at M._throwIfNoPty (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:5468),    at M.updateIcon (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:2232),    at Object.call (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:13:8402),    at f.onPromise (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4940),    at f.onRawMessage (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4299),    at /home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:3552,    at D.fire (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.S (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:6:32863),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[Error: Could not find pty with id "3",    at M._throwIfNoPty (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:5468),    at M.updateIcon (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:17:2232),    at Object.call (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:13:8402),    at f.onPromise (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4940),    at f.onRawMessage (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:4299),    at /home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:12:3552,    at D.fire (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:8:1712),    at process.S (/home/ec2-user/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/out/vs/platform/terminal/node/ptyHostMain.js:6:32863),    at process.emit (events.js:315:20),    at emit (internal/child_process.js:903:12),    at processTicksAndRejections (internal/process/task_queues.js:81:21)]
New EH opened, aborting shutdown
[19:35:54] New EH opened, aborting shutdown
